<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INAS-LP024" name="com.vrt.testcases.LoginTest" tests="17" failures="1" timestamp="29 Jul 2019 14:20:34 GMT" time="217.716" errors="0">
  <testcase name="LOGIN_016" time="14.491" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_004" time="4.245" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_001" time="6.805" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_003" time="3.049" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_020" time="50.239" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_007" time="5.807" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_012" time="9.392" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_014" time="12.900" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_009" time="14.404" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_005" time="14.988" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_017_018" time="27.307" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_019" time="28.064" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_002" time="3.630" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_010" time="3.608" classname="com.vrt.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	FAIL: The 1st User is allowed to Change its PW on 1st time Login expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
FAIL: The 1st User is allowed to Change its PW on 1st time Login expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.vrt.testcases.LoginTest.LOGIN_010(LoginTest.java:245)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOGIN_010 -->
  <testcase name="LOGIN_008" time="2.996" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_015" time="9.623" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_013" time="6.168" classname="com.vrt.testcases.LoginTest"/>
</testsuite> <!-- com.vrt.testcases.LoginTest -->
